### ISSUE TITLE
progress bar update error

### ISSUE THREAD

**Issue by TadLeonard** [TadLeonard/tfatool#7]
Progress bar (tqdm) can't be updated with the value `0`.

```
Traceback (most recent call last):
  File "/usr/local/bin/flashair-util", line 206, in <module>
    run()
  File "/usr/local/bin/flashair-util", line 120, in run
    sync_loop(filters, args)
  File "/usr/local/bin/flashair-util", line 153, in sync_loop
    _sync_loop(filters, args)
  File "/usr/local/bin/flashair-util", line 173, in _sync_loop
    _, new = next(new_files)
 File "/usr/local/lib/python3.5/dist-packages/tfatool/sync.py", line 146, in down_by_arrival
    down_by_files(new_arrivals, local_dir)
  File "/usr/local/lib/python3.5/dist-packages/tfatool/sync.py", line 171, in down_by_files
    _sync_remote_file(local_dir, f)
  File "/usr/local/lib/python3.5/dist-packages/tfatool/sync.py", line 211, in _sync_remote_file
    _stream_to_file(local_name, remote_file_info)
  File "/usr/local/lib/python3.5/dist-packages/tfatool/sync.py", line 218, in _stream_to_file
    _write_file_safely(local_name, fileinfo, streaming_file)
  File "/usr/local/lib/python3.5/dist-packages/tfatool/sync.py", line 237, in _write_file_safely
    raise e
  File "/usr/local/lib/python3.5/dist-packages/tfatool/sync.py", line 231, in _write_file_safely
    _write_file(local_path, fileinfo, response)
  File "/usr/local/lib/python3.5/dist-packages/tfatool/sync.py", line 248, in _write_file
    pbar.update(int(progress))
  File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 534, in update
    raise ValueError("n ({0}) cannot be less than 1".format(n))
ValueError: n (0) cannot be less than 1
```

**Comment by TadLeonard** [comment]
Fixed in v2.2.3
